services:
  tinyproxy:
    image: docker.io/kalaksi/tinyproxy
    restart: unless-stopped
    cap_drop:
      - ALL
    ports:
      # This correctly exposes port 8888 on the host machine
      - '8888:8888'
    environment:
      # --- Tinyproxy Settings (Kept as is) ---
      DISABLE_VIA_HEADER: 'yes'
      STAT_HOST: tinyproxy.stats
      MAX_CLIENTS: 100
      ALLOWED_NETWORKS: '127.0.0.1/8 10.0.0.0/8 91.99.55.112 178.156.165.233 157.180.28.131 37.27.95.101 37.27.4.175 37.27.219.67 95.173.205.155' # Ensure IPs needing access are listed here
      LOG_LEVEL: Connect
      TIMEOUT: 900
      # --- Coolify Management Variables (Keep these) ---
      COOLIFY_BRANCH: '"master"'
      COOLIFY_RESOURCE_UUID: tcs4s4okw4koo4cskk0wsosw
      COOLIFY_CONTAINER_NAME: tinyproxy-tcs4s4okw4koo4cskk0wsosw-210134855765
      COOLIFY_URL: 'https://p1.illuminati1010.com'
      COOLIFY_FQDN: p1.illuminati1010.com
    healthcheck:
      test:
        - CMD
        - curl
        - '-I'
        - '-H'
        - 'Host: tinyproxy.stats'
        - 'http://localhost:8888'
      interval: 5m
      timeout: 10s
      retries: 1
    container_name: tinyproxy-tcs4s4okw4koo4cskk0wsosw-210134855765
    # --- Keep Coolify Management Labels ---
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.415
      - coolify.applicationId=12
      - coolify.type=application
      - coolify.name=tinyproxy-tcs4s4okw4koo4cskk0wsosw-210134855765
      - coolify.resourceName=elementrcodedocker-tinyproxymaster-tcs4s4okw4koo4cskk0wsosw
      - coolify.projectName=llm-ai-master-project
      - coolify.serviceName=elementrcodedocker-tinyproxymaster-tcs4s4okw4koo4cskk0wsosw
      - coolify.environmentName=production
      - coolify.pullRequestId=0
    # --- REMOVED Traefik and Caddy labels ---
    # All lines starting with 'traefik.' or 'caddy_' have been removed.
    # --- Keep Coolify Networking ---
    networks:
      tcs4s4okw4koo4cskk0wsosw: null

# --- Keep the rest of the file as is (networks, volumes, configs, secrets sections) ---
networks:
  tcs4s4okw4koo4cskk0wsosw:
    name: tcs4s4okw4koo4cskk0wsosw
    external: true
volumes: { }
configs: { }
secrets: { }
